In [146]:
import pandas as pd
import numpy as np
import os

In [147]:
# disable display limit for pandas
pd.set_option('display.max_columns', None)


# Data loading, EDA and preprocessing

In [148]:
# read all file names in the directory
files = os.listdir('../data/raw')

# read all files into one dataframe
df = pd.DataFrame()
for file in files:
    df = pd.concat([df, pd.read_csv('../data/raw/' + file)], ignore_index=True)

In [149]:
# inspect the data
df.head()


Destination Port   Flow Duration   Total Fwd Packets  \
0               22.0           166.0                 1.0   
1            60148.0            83.0                 1.0   
2              123.0         99947.0                 1.0   
3              123.0         37017.0                 1.0   
4                0.0     111161336.0               147.0   

    Total Backward Packets  Total Length of Fwd Packets  \
0                      1.0                          0.0   
1                      2.0                          0.0   
2                      1.0                         48.0   
3                      1.0                         48.0   
4                      0.0                          0.0   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                           0.0                     0.0   
1                           0.0                     0.0   
2                          48.0                    48.0   
3                          48.0                    48.0   
4                           0.0                     0.0   

    Fwd Packet Length Min   Fwd Packet Length Mean   Fwd Packet Length Std  \
0                     0.0                      0.0                     0.0   
1                     0.0                      0.0                     0.0   
2                    48.0                     48.0                     0.0   
3                    48.0                     48.0                     0.0   
4                     0.0                      0.0                     0.0   

   Bwd Packet Length Max   Bwd Packet Length Min   Bwd Packet Length Mean  \
0                    0.0                     0.0                      0.0   
1                    0.0                     0.0                      0.0   
2                   48.0                    48.0                     48.0   
3                   48.0                    48.0                     48.0   
4                    0.0                     0.0                      0.0   

    Bwd Packet Length Std  Flow Bytes/s   Flow Packets/s   Flow IAT Mean  \
0                     0.0      0.000000     12048.192770        166.0000   
1                     0.0      0.000000     36144.578310         41.5000   
2                     0.0    960.509070        20.010606      99947.0000   
3                     0.0   2593.403031        54.029230      37017.0000   
4                     0.0      0.000000         1.322402     761379.0137   

    Flow IAT Std   Flow IAT Max   Flow IAT Min  Fwd IAT Total   Fwd IAT Mean  \
0   0.000000e+00          166.0          166.0            0.0         0.0000   
1   1.060660e+01           49.0           34.0            0.0         0.0000   
2   0.000000e+00        99947.0        99947.0            0.0         0.0000   
3   0.000000e+00        37017.0        37017.0            0.0         0.0000   
4   2.539814e+06     13600000.0            0.0    111000000.0    761379.0137   

    Fwd IAT Std   Fwd IAT Max   Fwd IAT Min  Bwd IAT Total   Bwd IAT Mean  \
0         0.000           0.0           0.0            0.0            0.0   
1         0.000           0.0           0.0           49.0           49.0   
2         0.000           0.0           0.0            0.0            0.0   
3         0.000           0.0           0.0            0.0            0.0   
4   2539814.273    13600000.0           0.0            0.0            0.0   

    Bwd IAT Std   Bwd IAT Max   Bwd IAT Min  Fwd PSH Flags   Bwd PSH Flags  \
0           0.0           0.0           0.0            0.0             0.0   
1           0.0          49.0          49.0            0.0             0.0   
2           0.0           0.0           0.0            0.0             0.0   
3           0.0           0.0           0.0            0.0             0.0   
4           0.0           0.0           0.0            0.0             0.0   

    Fwd URG Flags   Bwd URG Flags   Fwd Header Length   Bwd Header Length  \
0             0.0             0.0                32.0 

In [150]:
# summary statistics
df.describe()

Destination Port   Flow Duration   Total Fwd Packets  \
count       2.830743e+06    2.830743e+06        2.830743e+06   
mean        8.071483e+03    1.478566e+07        9.361160e+00   
std         1.828363e+04    3.365374e+07        7.496728e+02   
min         0.000000e+00   -1.300000e+01        1.000000e+00   
25%         5.300000e+01    1.550000e+02        2.000000e+00   
50%         8.000000e+01    3.131600e+04        2.000000e+00   
75%         4.430000e+02    3.204828e+06        5.000000e+00   
max         6.553500e+04    1.200000e+08        2.197590e+05   

        Total Backward Packets  Total Length of Fwd Packets  \
count             2.830743e+06                 2.830743e+06   
mean              1.039377e+01                 5.493024e+02   
std               9.973883e+02                 9.993589e+03   
min               0.000000e+00                 0.000000e+00   
25%               1.000000e+00                 1.200000e+01   
50%               2.000000e+00                 6.200000e+01   
75%               4.000000e+00                 1.870000e+02   
max               2.919220e+05                 1.290000e+07   

        Total Length of Bwd Packets   Fwd Packet Length Max  \
count                  2.830743e+06            2.830743e+06   
mean                   1.616264e+04            2.075999e+02   
std                    2.263088e+06            7.171848e+02   
min                    0.000000e+00            0.000000e+00   
25%                    0.000000e+00            6.000000e+00   
50%                    1.230000e+02            3.700000e+01   
75%                    4.820000e+02            8.100000e+01   
max                    6.554530e+08            2.482000e+04   

        Fwd Packet Length Min   Fwd Packet Length Mean  \
count            2.830743e+06             2.830743e+06   
mean             1.871366e+01             5.820194e+01   
std              6.033935e+01             1.860912e+02   
min              0.000000e+00             0.000000e+00   
25%              0.000000e+00             6.000000e+00   
50%              2.000000e+00             3.400000e+01   
75%              3.600000e+01             5.000000e+01   
max              2.325000e+03             5.940857e+03   

        Fwd Packet Length Std  Bwd Packet Length Max   Bwd Packet Length Min  \
count            2.830743e+06           2.830743e+06            2.830743e+06   
mean             6.891013e+01           8.708495e+02            4.104958e+01   
std              2.811871e+02           1.946367e+03            6.886260e+01   
min              0.000000e+00           0.000000e+00            0.000000e+00   
25%              0.000000e+00           0.000000e+00            0.000000e+00   
50%              0.000000e+00           7.900000e+01            0.000000e+00   
75%              2.616295e+01           2.800000e+02            7.700000e+01   
max              7.125597e+03           1.953000e+04            2.896000e+03   

        Bwd Packet Length Mean   Bwd Packet Length Std  Flow Bytes/s  \
count             2.830743e+06            2.830743e+06  2.829385e+06   
mean              3.059493e+02            3.353257e+02           inf   
std               6.052568e+02            8.396932e+02           NaN   
min               0.000000e+00            0.000000e+00 -2.610000e+08   
25%               0.000000e+00            0.000000e+00  1.193197e+02   
50%               7.200000e+01            0.000000e+00  4.595549e+03   
75%               1.810000e+02            7.794054e+01  1.666667e+05   
max               5.800500e+03            8.194660e+03           inf   

        Flow Packets/s   Flow IAT Mean   Flow IAT Std   Flow IAT Max  \
count     2.830743e+06    2.830743e+06   2.830743e+06   2.830743e+06   
mean               inf    1.298449e+06   2.919271e+06   9.182475e+06   
std                NaN    4.507944e+06   8.045870e+06   2.445954e+07   
min      -2.000000e+06   -1.300000e+01   0.000000e+00  -1.300000e+01   
25%       3.446226e+00    6.366667e+01   0

In [151]:
# column names
df.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', '

In [152]:
# drop last column
df.drop(df.columns[-1], axis=1, inplace=True)

# check column names
df.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', '

In [153]:
# remove whitespace from column names
df.columns = df.columns.str.strip()

# clean the 
df['Label'] = df['Label'].str.replace(' � ', ' ')


In [154]:
# check for missing values
df.isnull().sum()

Destination Port               7
Flow Duration                  7
Total Fwd Packets              7
Total Backward Packets         7
Total Length of Fwd Packets    7
                              ..
Idle Mean                      7
Idle Std                       7
Idle Max                       7
Idle Min                       7
Label                          7
Length: 79, dtype: int64

In [155]:
# see label distribution for missing values
print("Value counts for label for missing rows: ")
print(df[df.isnull().any(axis=1)]['Label'].value_counts())

# see how many other rows are there for 'DoS Hulk' label
print("Other rows with DoS Hulk label: ", df[df['Label'] == 'DoS Hulk'].shape[0])

# other rows with BENIGN label
print("Other rows with BENIGN label: ", df[df['Label'] == 'BENIGN'].shape[0])

Value counts for label for missing rows: 
DoS Hulk    949
BENIGN      409
Name: Label, dtype: int64
Other rows with DoS Hulk label:  231073
Other rows with BENIGN label:  2273097


In [156]:
# since we have enough data for DoS Hulk and BENIGN, we can drop the rows with missing values
# drop rows with inf values too
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

# check for missing values
df.isnull().sum()

Destination Port               0
Flow Duration                  0
Total Fwd Packets              0
Total Backward Packets         0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
Idle Std                       0
Idle Max                       0
Idle Min                       0
Label                          0
Length: 79, dtype: int64

In [157]:
# different labels
df['Label'].value_counts()

BENIGN                      2271320
DoS Hulk                     230124
PortScan                     158804
DDoS                         128025
DoS GoldenEye                 10293
FTP-Patator                    7935
SSH-Patator                    5897
DoS slowloris                  5796
DoS Slowhttptest               5499
Bot                            1956
Web Attack Brute Force         1507
Web Attack XSS                  652
Infiltration                     36
Web Attack Sql Injection         21
Heartbleed                       11
Name: Label, dtype: int64

In [158]:
# filter the data to only include DoS and DDos attacks and Brute Force and XXS attacks
df = df[df['Label'].isin(['BENIGN', 'PortScan', 'FTP-Patator', 'SSH-Patator' ,'DoS Hulk', 'DoS GoldenEye', 'DoS slowloris', 'DoS Slowhttptest', 'DDoS', 'Web Attack Brute Force'])]

# PortScan - activity performed by a hacker to identify open ports and services available on a host, and identify potential weaknesses
# FTP-Patator - brute force attack on FTP server
# SSH-Patator - brute force attack on SSH server
# DoS Hulk - denial of service attack on web server
# DoS GoldenEye - denial of service attack on web server
# DoS slowloris - denial of service attack on web server
# DoS Slowhttptest - denial of service attack on web server
# DDoS - distributed denial of service attack on web server
# Brute Force - brute force attack on web server

# group together all DoS attacks
df['Label'].replace(['DoS Hulk', 'DoS GoldenEye', 'DoS slowloris', 'DoS Slowhttptest'], 'DoS', inplace=True)

In [159]:
# new label distribution
df['Label'].value_counts()

BENIGN                    2271320
DoS                        251712
PortScan                   158804
DDoS                       128025
FTP-Patator                  7935
SSH-Patator                  5897
Web Attack Brute Force       1507
Name: Label, dtype: int64

In [160]:
# final data
df.head()

Destination Port  Flow Duration  Total Fwd Packets  Total Backward Packets  \
0              22.0          166.0                1.0                     1.0   
1           60148.0           83.0                1.0                     2.0   
2             123.0        99947.0                1.0                     1.0   
3             123.0        37017.0                1.0                     1.0   
4               0.0    111161336.0              147.0                     0.0   

   Total Length of Fwd Packets  Total Length of Bwd Packets  \
0                          0.0                          0.0   
1                          0.0                          0.0   
2                         48.0                         48.0   
3                         48.0                         48.0   
4                          0.0                          0.0   

   Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
0                    0.0                    0.0                     0.0   
1                    0.0                    0.0                     0.0   
2                   48.0                   48.0                    48.0   
3                   48.0                   48.0                    48.0   
4                    0.0                    0.0                     0.0   

   Fwd Packet Length Std  Bwd Packet Length Max  Bwd Packet Length Min  \
0                    0.0                    0.0                    0.0   
1                    0.0                    0.0                    0.0   
2                    0.0                   48.0                   48.0   
3                    0.0                   48.0                   48.0   
4                    0.0                    0.0                    0.0   

   Bwd Packet Length Mean  Bwd Packet Length Std  Flow Bytes/s  \
0                     0.0                    0.0      0.000000   
1                     0.0                    0.0      0.000000   
2                    48.0                    0.0    960.509070   
3                    48.0                    0.0   2593.403031   
4                     0.0                    0.0      0.000000   

   Flow Packets/s  Flow IAT Mean  Flow IAT Std  Flow IAT Max  Flow IAT Min  \
0    12048.192770       166.0000  0.000000e+00         166.0         166.0   
1    36144.578310        41.5000  1.060660e+01          49.0          34.0   
2       20.010606     99947.0000  0.000000e+00       99947.0       99947.0   
3       54.029230     37017.0000  0.000000e+00       37017.0       37017.0   
4        1.322402    761379.0137  2.539814e+06    13600000.0           0.0   

   Fwd IAT Total  Fwd IAT Mean  Fwd IAT Std  Fwd IAT Max  Fwd IAT Min  \
0            0.0        0.0000        0.000          0.0          0.0   
1            0.0        0.0000        0.000          0.0          0.0   
2            0.0        0.0000        0.000          0.0          0.0   
3            0.0        0.0000        0.000          0.0          0.0   
4    111000000.0   761379.0137  2539814.273   13600000.0          0.0   

   Bwd IAT Total  Bwd IAT Mean  Bwd IAT Std  Bwd IAT Max  Bwd IAT Min  \
0            0.0           0.0          0.0          0.0          0.0   
1           49.0          49.0          0.0         49.0         49.0   
2            0.0           0.0          0.0          0.0          0.0   
3            0.0           0.0          0.0          0.0          0.0   
4            0.0           0.0          0.0          0.0          0.0   

   Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  Bwd URG Flags  \
0            0.0            0.0            0.0            0.0   
1            0.0            0.0            0.0            0.0   
2            0.0            0.0            0.0            0.0   
3            0.0            0.0            0.0            0.0   
4            0.0            0.0            0.0            0.0   

   Fwd Header Length  Bwd Header Length  Fwd Packets/s  Bwd Packets/s  \
0               32.0             

In [161]:
# finally reshuffle the data
df = df.sample(frac=1).reset_index(drop=True)

# Selecting relevant features

In [165]:
# limit the number of features to the most influential ones
# first, we need to encode the labels
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])

# store the label encoding
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))


In [166]:
# correlation matrix
corr_matrix = df.corr()

In [167]:
corr_matrix

Destination Port  Flow Duration  \
Destination Port                     1.000000      -0.151554   
Flow Duration                       -0.151554       1.000000   
Total Fwd Packets                   -0.004222       0.020770   
Total Backward Packets              -0.003937       0.019613   
Total Length of Fwd Packets          0.011968       0.067090   
...                                       ...            ...   
Idle Mean                           -0.112483       0.768009   
Idle Std                             0.010514       0.243087   
Idle Max                            -0.108070       0.779499   
Idle Min                            -0.114526       0.738301   
Label                               -0.092458       0.106914   

                             Total Fwd Packets  Total Backward Packets  \
Destination Port                     -0.004222               -0.003937   
Flow Duration                         0.020770                0.019613   
Total Fwd Packets                     1.000000                0.999077   
Total Backward Packets                0.999077                1.000000   
Total Length of Fwd Packets           0.380616                0.374879   
...                                        ...                     ...   
Idle Mean                             0.001819                0.001422   
Idle Std                              0.000798                0.000483   
Idle Max                              0.001903                0.001452   
Idle Min                              0.001671                0.001328   
Label                                -0.003456               -0.003262   

                             Total Length of Fwd Packets  \
Destination Port                                0.011968   
Flow Duration                                   0.067090   
Total Fwd Packets                               0.380616   
Total Backward Packets                          0.374879   
Total Length of Fwd Packets                     1.000000   
...                                                  ...   
Idle Mean                                       0.023816   
Idle Std                                        0.028071   
Idle Max                                        0.027351   
Idle Min                                        0.019637   
Label                                          -0.017563   

                             Total Length of Bwd Packets  \
Destination Port                               -0.003075   
Flow Duration                                   0.016146   
Total Fwd Packets                               0.997025   
Total Backward Packets                          0.994451   
Total Length of Fwd Packets                     0.370778   
...                                                  ...   
Idle Mean                                       0.000808   
Idle Std                                        0.000105   
Idle Max                                        0.000797   
Idle Min                                        0.000789   
Label                                          -0.002410   

                             Fwd Packet Length Max  Fwd Packet Length Min  \
Destination Port                          0.098679              -0.045311   
Flow Duration                             0.274222              -0.105488   
Total Fwd Packets                         0.009280              -0.002986   
Total Backward Packets                    0.008994              -0.002600   
Total Length of Fwd Packets               0.202305              -0.000128   
...                                            ...                    ...   
Idle Mean                                 0.181772              -0.071516   
Idle Std                                  0.178721              -0.030014   
Idle Max                                  0.200262              -0.073634   
Idle Min                                  0.157521              -0.067638   
Label                                    -0.066281              -0.121949   

    

In [168]:
# correlation with label
corr_matrix['Label'].sort_values(ascending=False)

Label                    1.000000
PSH Flag Count           0.279934
Fwd IAT Std              0.260920
Bwd Packet Length Std    0.242862
Idle Mean                0.241019
                           ...   
Fwd Avg Packets/Bulk          NaN
Fwd Avg Bulk Rate             NaN
Bwd Avg Bytes/Bulk            NaN
Bwd Avg Packets/Bulk          NaN
Bwd Avg Bulk Rate             NaN
Name: Label, Length: 79, dtype: float64

In [169]:
# use only the columns which correlate with the label is greater than 0.1 or smaller than -0.1
# columns to keep
columns = corr_matrix[(corr_matrix['Label'] > 0.1) | (corr_matrix['Label'] < -0.1)].index

# drop all other columns
df = df[columns]

In [170]:
df.head()

Flow Duration  Fwd Packet Length Min  Bwd Packet Length Max  \
0      5263136.0                   34.0                   95.0   
1            3.0                    0.0                    0.0   
2    116190115.0                    0.0                 2816.0   
3       158516.0                    0.0                 5840.0   
4        46397.0                   61.0                  223.0   

   Bwd Packet Length Min  Bwd Packet Length Mean  Bwd Packet Length Std  \
0                   95.0               95.000000               0.000000   
1                    0.0                0.000000               0.000000   
2                    0.0              191.888889             660.392654   
3                    0.0             1934.500000            2538.919278   
4                  223.0              223.000000               0.000000   

   Flow IAT Std  Flow IAT Max  Fwd IAT Total   Fwd IAT Std  Fwd IAT Max  \
0  5.964099e+05     2000173.0      3031037.0  7.841599e+05    2000173.0   
1  0.000000e+00           3.0            3.0  0.000000e+00          3.0   
2  4.520030e+06    10028517.0    116190115.0  5.019181e+06   10144032.0   
3  5.577021e+04      157838.0          570.0  3.988082e+02        567.0   
4  0.000000e+00       46397.0            0.0  0.000000e+00          0.0   

   Min Packet Length  Max Packet Length  Packet Length Mean  \
0               34.0               95.0           62.705882   
1                0.0               53.0           35.333333   
2                0.0             2816.0          103.682927   
3                0.0             5840.0         1163.300000   
4               61.0              223.0          115.000000   

   Packet Length Std  Packet Length Variance  FIN Flag Count  PSH Flag Count  \
0          31.384241            9.849706e+02             0.0             0.0   
1          30.599564            9.363333e+02             0.0             0.0   
2         443.650563            1.968258e+05             0.0             1.0   
3        2138.329153            4.572452e+06             0.0             1.0   
4          93.530744            8.748000e+03             0.0             0.0   

   URG Flag Count  Average Packet Size  Avg Bwd Segment Size     Idle Mean  \
0             0.0            66.625000             95.000000  0.000000e+00   
1             0.0            53.000000              0.000000  0.000000e+00   
2             0.0           106.275000            191.888889  1.002345e+07   
3             0.0          1292.555556           1934.500000  0.000000e+00   
4             0.0           172.500000            223.000000  0.000000e+00   

     Idle Max   Idle Min  Label  
0         0.0        0.0      0  
1         0.0        0.0      0  
2  10028517.0  9999509.0      0  
3         0.0        0.0      1  
4         0.0        0.0      0

# Classification model for attacks - training

In [171]:
# develop a simple classifier to detect the different types of attacks

# separate features and labels
X = df.drop('Label', axis=1)
y = df['Label']

# split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

# check the shape of the train and test sets
print("Shape of train set: ", X_train.shape)
print("Shape of test set: ", X_test.shape)

# check the label distribution in train and test sets
print("Label distribution in train set: ")
print(y_train.value_counts())

print("Label distribution in test set: ")
print(y_test.value_counts())

# scale the features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Shape of train set:  (2118900, 24)
Shape of test set:  (706300, 24)
Label distribution in train set: 
0    1703578
2     188907
4     118821
1      96079
3       5974
5       4416
6       1125
Name: Label, dtype: int64
Label distribution in test set: 
0    567742
2     62805
4     39983
1     31946
3      1961
5      1481
6       382
Name: Label, dtype: int64


In [172]:
# train a very efficient version of the Random Forest Classifier - LightGBM
import lightgbm as lgb
classifier = lgb.LGBMClassifier()
classifier.fit(X_train, y_train)

LGBMClassifier()

# Classification model - evalutation

In [173]:
# evaluate model performance, translating the label encoding back to the original labels
from sklearn.metrics import classification_report
y_pred = classifier.predict(X_test)
print(classification_report(y_test, y_pred, target_names=label_mapping.keys()))

                        precision    recall  f1-score   support

                BENIGN       0.98      0.98      0.98    567742
                  DDoS       0.92      0.94      0.93     31946
                   DoS       0.84      0.85      0.84     62805
           FTP-Patator       0.00      0.00      0.00      1961
              PortScan       0.99      0.99      0.99     39983
           SSH-Patator       0.00      0.00      0.00      1481
Web Attack Brute Force       0.24      0.19      0.21       382

              accuracy                           0.96    706300
             macro avg       0.57      0.57      0.57    706300
          weighted avg       0.96      0.96      0.96    706300



In [174]:
# get accuracy score
from sklearn.metrics import accuracy_score
print("Accuracy score: ", accuracy_score(y_test, y_pred))


Accuracy score:  0.959613478691774


In [175]:
# get confusion matrix with original labels
from sklearn.metrics import confusion_matrix
print("Confusion matrix: ")
print(confusion_matrix(y_test, y_pred))


Confusion matrix: 
[[554741   1067   7366   2729    483   1131    225]
 [   712  29989   1121    119      5      0      0]
 [  7808    908  53221    397     17    446      8]
 [   533    669    749      8      2      0      0]
 [   110      2    129      0  39739      3      0]
 [   853      0    613      8      3      4      0]
 [   299      0      9      0      0      1     73]]


In [178]:
# get feature importances with original column names and also get top 5 features
feature_importances = pd.DataFrame(classifier.feature_importances_, index=X.columns, columns=['Importance']).sort_values('Importance', ascending=False)
print("Top 10 features: ")
print(feature_importances.head(10))

Top 10 features: 
                        Importance
Flow Duration                 2706
Fwd IAT Total                 2043
Flow IAT Std                  1859
Flow IAT Max                  1712
Fwd IAT Std                   1708
Fwd IAT Max                   1413
Average Packet Size           1110
Bwd Packet Length Mean        1094
Packet Length Mean            1004
Packet Length Std              932
